### ISSUE TITLE
Fetch all subcounties in a particular district

### ISSUE THREAD

**Issue by kusaasira** [kusaasira/uganda-geo-data#4]
Create a method that fetches only sub counties from a particular parsed district.

Follow Appblocks Standards and Guidelines.

At the moment, one has to go through a chain to fetch subcounties i.e. see code block below.

```
$geo = new Geo();
$data = $geo
        ->districts('Mukono')
        ->counties('Mukono Municipality')
        ->sub_counties->all();
```

Refactor this to accept fetching subcounties as indicated below;

```
$geo = new Geo();
$data = $geo
        ->districts('Mukono')
        ->sub_counties->all();
```

For more information on the structure, checkout the repo [wiki](https://github.com/kusaasira/uganda-geo-data/wiki).

Follow PSR-12 coding standards and guidelines.

**Comment by kusaasira** [comment]
@Marshud I have updated the issue description to provide more insight on how to work on this.

**Comment by Marshud** [comment]
Thank you @kusaasira I will take keen note

**Comment by kusaasira** [comment]
@Marshud this was all catered for in a PR referenced above by @RoadSigns . Allow me close this issue.
