### ISSUE TITLE
Refactor codebase

### ISSUE THREAD

**Issue by kusaasira** [kusaasira/uganda-geo-data#8]
Refactor codebase to follow DRY / SOLID and reduce coupling.

Follow PSR-12 coding standards and guidelines.

**Comment by RoadSigns** [comment]
@kusaasira Are you able to provide a link to the Appblocks Standards and Guidelines to ensure that they are being following correctly by anyone that picks these up?

**Comment by kusaasira** [comment]
@RoadSigns since you added linting support for PSR-12. I'm suggesting we switch to following the PSR-12 coding standards and guidelines. Wouldn't that suffice?

**Comment by RoadSigns** [comment]
@kusaasira 
Yeah, that would resolve a lot of the coding standards. For the tackling of "DRY", I think we could look into using PHPStan (https://phpstan.org/) for that or just use code reviews via pull requests to allow people to capture that themselves.

**Comment by RoadSigns** [comment]
@kusaasira By the way, there is also a script now in the package called `composer cs-fix` which will auto fix your coding standards to meet the PSR-12. So following the standard is already implemented and is now enforced via the tests

**Comment by kusaasira** [comment]
@RoadSigns the `composer cs-fix` is a great deal here. Adding a note that it should follow PSR-12 is a heads up though.

Concerning PHP Stan, If you are familiar, I would be grateful if you take lead here as am not that conversant though curious here.

**Comment by RoadSigns** [comment]
@kusaasira 
Sure, I can set up PHPStan in a pull request and we can discuss there around the setup.
For PHPStan, do you want it to be run via Github Actions as well?

**Comment by kusaasira** [comment]
@RoadSigns yes, opening a PR sounds good.
 
Yes, setting it up via Github Actions.

**Comment by RoadSigns** [comment]
@kusaasira So turns out we were unable to achieve PHPStan above level 1.
https://phpstan.org/user-guide/rule-levels

So I've taken on the refactoring on the package so we are able to support searches across all scenarios.
Rough example of this is:

```
$uganda = new Uganda();
$uganda->district('Bukomansimbi')->villages();
```

This will give us all of the Villages inside of Bukomansimbi.
I believe this might resolve #4 and #6 

From this refactor we are able to follow PSR-12 and also support up to PHPStan Level 9.
Refactor Pull Request #10

**Comment by kusaasira** [comment]
@RoadSigns you did some good work over there in this PR [#10](https://github.com/kusaasira/uganda-geo-data/pull/10). The previous codebase was locked into only json encoded data. Kudos!
